version: "3"
services:
  shevek:
    build: .
    depends_on:
      - mongo
    ports:
      - "${SHEVEK_PORT}:4000"
    environment:
      - MONGODB_URI=mongodb://mongo/shevek

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - ./tmp/mongo:/data/db
